import { LanguageCode } from '../types/marine';

export interface LanguageMeta {
  code: LanguageCode;
  label: string;
  nativeLabel: string;
  speechVoiceCode: string;
  region: string;
}

export const SUPPORTED_LANGUAGES: LanguageMeta[] = [
  { code: 'en', label: 'English', nativeLabel: 'English', speechVoiceCode: 'en-IN', region: 'All Coastal Ports' },
  { code: 'hi', label: 'Hindi', nativeLabel: 'हिन्दी', speechVoiceCode: 'hi-IN', region: 'National' },
  { code: 'mr', label: 'Marathi', nativeLabel: 'मराठी', speechVoiceCode: 'mr-IN', region: 'Maharashtra & Konkan' },
  { code: 'ta', label: 'Tamil', nativeLabel: 'தமிழ்', speechVoiceCode: 'ta-IN', region: 'Tamil Nadu & Puducherry' },
  { code: 'te', label: 'Telugu', nativeLabel: 'తెలుగు', speechVoiceCode: 'te-IN', region: 'Andhra Pradesh' },
  { code: 'bn', label: 'Bengali', nativeLabel: 'বাংলা', speechVoiceCode: 'bn-IN', region: 'West Bengal & Sundarbans' },
  { code: 'gu', label: 'Gujarati', nativeLabel: 'ગુજરાતી', speechVoiceCode: 'gu-IN', region: 'Gujarat Coast' },
  { code: 'ml', label: 'Malayalam', nativeLabel: 'മലയാളം', speechVoiceCode: 'ml-IN', region: 'Kerala & Lakshadweep' },
  { code: 'kn', label: 'Kannada', nativeLabel: 'ಕನ್ನಡ', speechVoiceCode: 'kn-IN', region: 'Karnataka Coastal' },
  { code: 'or', label: 'Odia', nativeLabel: 'ଓଡ଼ିଆ', speechVoiceCode: 'or-IN', region: 'Odisha Marine' },
];

export const TRANSLATIONS: Record<LanguageCode, Record<string, string>> = {
  en: {
    app_title: 'SagarMitra',
    app_subtitle: 'Marine Intelligence & Decision Support System',
    role_fisherman: 'Fisherman',
    role_authority: 'Coast Authority',
    role_researcher: 'Ocean Analytics',
    role_data_fusion: 'Grid Data B2',
    status_suitable: 'SAFE TO GO FISHING',
    status_moderate: 'MODERATE SEA - CAUTION',
    status_unsafe: 'DANGER - DO NOT ENTER SEA',
    safety_score: 'Sea Safety Score',
    pfz_suitability: 'Fish Concentration (PFZ)',
    best_pfz_zone: 'Best Fishing Zone',
    best_window: 'Best Fishing Time Window',
    recommended_route: 'Recommended Safe Route',
    avoid_corridor: 'Hazards to Avoid',
    marine_anomaly: 'Sea Risk Flag',
    return_before: 'Return to Port Before',
    last_synced: 'Last Synchronized',
    offline_mode_active: 'Offline Mode (Showing Stored Info)',
    listen_audio: 'Tap to Listen (Voice)',
    ask_ai_placeholder: 'Ask in your voice or text (e.g. Can I go fishing?)...',
    btn_submit_catch: 'Log Catch Report',
    btn_sos: 'Emergency SOS (Mayday)',
    btn_inspect_reasoning: 'View Decision Reason',
    cell_b2_title: 'Grid Cell B2 Ocean Telemetry',
    species_likely: 'Likely Fish Stocks',
    sunlight_mode: 'Sunlight Mode',
    bridge_mode: 'Night Mode',
    voice_script_suitable: 'Fishing is suitable this morning. Best zone is 16 km southwest in Cell B2 with 87 percent fish probability. Best fishing window is 6 to 10 AM. Avoid the northern shipping corridor and return safely before 11:30 AM.',
    voice_script_unsafe: 'Warning! Sea conditions are dangerous. Wave height and wind exceed safe limits. Do not enter the sea. Stay safely at port.',
    voice_script_moderate: 'Sea conditions are moderate. Undertake only short inshore voyage and return before afternoon when waves increase.',
  },
  hi: {
    app_title: 'सागरमित्र',
    app_subtitle: 'समुद्री निर्णय एवं सुरक्षा प्रणाली',
    role_fisherman: 'मछुआरा',
    role_authority: 'तटरक्षक बल',
    role_researcher: 'समुद्री अनुसंधान',
    role_data_fusion: 'डेटा ग्रिड B2',
    status_suitable: 'मछली पकड़ने के लिए सुरक्षित',
    status_moderate: 'मध्यम स्थिति - सावधानी बरतें',
    status_unsafe: 'खतरा - समुद्र में न जाएं (नो-गो)',
    safety_score: 'समुद्री सुरक्षा स्कोर',
    pfz_suitability: 'मछली संभावित क्षेत्र (PFZ)',
    best_pfz_zone: 'सर्वोत्तम मत्स्य क्षेत्र',
    best_window: 'मछली पकड़ने का सही समय',
    recommended_route: 'सुरक्षित समुद्री रास्ता',
    avoid_corridor: 'इन रास्तों से बचें',
    marine_anomaly: 'मौसम जोखिम स्तर',
    return_before: 'बंदरगाह वापसी का समय',
    last_synced: 'अंतिम अपडेट',
    offline_mode_active: 'ऑफ़लाइन मोड सक्रिय (कैश डेटा)',
    listen_audio: 'आवाज़ में सुनें (ऑडियो)',
    ask_ai_placeholder: 'बोलकर या लिखकर पूछें (उदा. क्या कल सुबह समुद्र सुरक्षित है?)...',
    btn_submit_catch: 'पकड़ी गई मछली दर्ज करें',
    btn_sos: 'आपातकालीन SOS बटन',
    btn_inspect_reasoning: 'एआई निर्णय का कारण देखें',
    cell_b2_title: 'ग्रिड सेल B2 समुद्री डेटा',
    species_likely: 'संभावित मछलियां',
    sunlight_mode: 'धूप मोड (दिन)',
    bridge_mode: 'रात का मोड',
    voice_script_suitable: 'आज सुबह समुद्र में जाना सुरक्षित है। सबसे अच्छा मत्स्य क्षेत्र 16 किलोमीटर दक्षिण-पश्चिम सेल B2 में है, जहाँ 87% मछली मिलने की संभावना है। सुबह 6 से 10 बजे तक का समय सर्वोत्तम है। उत्तरी जहाज मार्ग से बचें और दोपहर 11:30 से पहले लौट आएं।',
    voice_script_unsafe: 'चेतावनी! समुद्र में ऊंची लहरें और तेज हवाएं हैं। समुद्र में न जाएं। बंदरगाह पर ही रहें।',
    voice_script_moderate: 'समुद्र की स्थिति मध्यम है। केवल पास के क्षेत्र में जाएं और दोपहर से पहले सुरक्षित लौट आएं।',
  },
  mr: {
    app_title: 'सागरमित्र',
    app_subtitle: 'कोळी बांधव सागरी निर्णय सहाय्यक',
    role_fisherman: 'कोळी बांधव',
    role_authority: 'तटरक्षक प्राधिकरण',
    role_researcher: 'सागरी संशोधक',
    role_data_fusion: 'डेटा ग्रीड B2',
    status_suitable: 'मासेमारीसाठी सुरक्षित व अनुकूल',
    status_moderate: 'मध्यम परिस्थिती - सावधगिरी बाळगा',
    status_unsafe: 'धोकादायक - समुद्रात जाऊ नका (नो-गो)',
    safety_score: 'सागरी सुरक्षा गुण',
    pfz_suitability: 'मत्स्य संपत्ती क्षेत्र (PFZ)',
    best_pfz_zone: 'उत्तम मासेमारी क्षेत्र',
    best_window: 'मासेमारीसाठी सर्वोत्तम वेळ',
    recommended_route: 'शिफारस केलेला सुरक्षित मार्ग',
    avoid_corridor: 'टाळावयाचे धोकेदायक मार्ग',
    marine_anomaly: 'सागरी हवामान धोका',
    return_before: 'बंदरावर परतण्याची वेळ',
    last_synced: 'शेवटचे अद्यतन',
    offline_mode_active: 'ऑफलाईन मोड (साठवलेली माहिती)',
    listen_audio: 'मराठीत ऐका (ऑडिओ)',
    ask_ai_placeholder: 'सागरमित्राला विचारा (उदा. मी उद्या मासेमारीला जाऊ का?)...',
    btn_submit_catch: 'मिळालेल्या मासळीची नोंद',
    btn_sos: 'आपत्कालीन SOS मदत',
    btn_inspect_reasoning: 'निर्णयाचे कारण पाहा',
    cell_b2_title: 'ग्रीड सेल B2 सागरी टेलिमेट्री',
    species_likely: 'संभाव्य मासळी',
    sunlight_mode: 'उन्हाचा मोड (दिवस)',
    bridge_mode: 'रात्रीचा मोड',
    voice_script_suitable: 'आज सकाळी मासेमारीसाठी हवामान अनुकूल आहे. सर्वोत्तम मत्स्य क्षेत्र नैऋत्य दिशेला 16 किमी अंतरावर सेल B2 मध्ये आहे. सर्वोत्तम वेळ सकाळी 6 ते 10 आहे. मोठ्या जहाजांचा मार्ग टाळा आणि सकाळी 11:30 च्या आधी बंदरात परत या.',
    voice_script_unsafe: 'धोक्याचा इशारा! समुद्रात मोठी लाट आणि सोसाट्याचा वारा आहे. समुद्रात जाऊ नका. बंदरातच थांबा.',
    voice_script_moderate: 'समुद्रात मध्यम लाटा आहेत. जास्त दूर जाऊ नका आणि दुपारपूर्वी परत या.',
  },
  ta: {
    app_title: 'சாகர்மித்ரா',
    app_subtitle: 'மீனவர் கடல்சார் பாதுகாப்பு & முடிவெடுக்கும் தளம்',
    role_fisherman: 'மீனவர்',
    role_authority: 'கடலோர காவல்படை',
    role_researcher: 'கடல் ஆராய்ச்சி',
    role_data_fusion: 'தரவு கட்டம் B2',
    status_suitable: 'மீன்பிடிக்க பாதுகாப்பானது',
    status_moderate: 'மிதமான கடல் - எச்சரிக்கையுடன் செல்லவும்',
    status_unsafe: 'ஆபத்து - கடலுக்கு செல்ல வேண்டாம்',
    safety_score: 'பாதுகாப்பு மதிப்பெண்',
    pfz_suitability: 'மீன் கிடைக்கும் வாய்ப்பு (PFZ)',
    best_pfz_zone: 'சிறந்த மீன்பிடி மண்டலம்',
    best_window: 'சிறந்த மீன்பிடி நேரம்',
    recommended_route: 'பரிந்துரைக்கப்பட்ட பாதை',
    avoid_corridor: 'தவிர்க்க வேண்டிய பகுதிகள்',
    marine_anomaly: 'கடல்சார் அசாதாரண ஆபத்து',
    return_before: 'கரை திரும்ப வேண்டிய நேரம்',
    last_synced: 'கடைசி புதுப்பிப்பு',
    offline_mode_active: 'ஆஃப்லைன் பயன்முறை செயலில் உள்ளது',
    listen_audio: 'தமிழில் கேட்கவும் (ஆடியோ)',
    ask_ai_placeholder: 'கேள்வி கேளுங்கள் (उदा. நாளை கடலுக்கு செல்லலாமா?)...',
    btn_submit_catch: 'பிடிபட்ட மீன் விவரம்',
    btn_sos: 'அவசர SOS உதவி',
    btn_inspect_reasoning: 'முடிவு காரணத்தைப் பார்க்கவும்',
    cell_b2_title: 'கட்டம் B2 கடல்சார் தரவு',
    species_likely: 'சாத்தியமான மீன்கள்',
    sunlight_mode: 'பகல் ஒளி முறை',
    bridge_mode: 'இரவு முறை',
    voice_script_suitable: 'இன்று காலை மீன்பிடிக்க ஏற்றது. சிறந்த மீன்பிடி மண்டலம் 16 கிமீ தென்மேற்கில் செல் B2 இல் உள்ளது. காலை 6 முதல் 10 மணி வரை சிறந்த நேரம். வடக்கு கப்பல் பாதையைத் தவிர்க்கவும். காலை 11:30 மணிக்குள் கரை திரும்பவும்.',
    voice_script_unsafe: 'எச்சரிக்கை! கடல் கொந்தளிப்பாக உள்ளது. பெரிய அலைகள் மற்றும் பலத்த காற்று வீசுகிறது. கடலுக்கு செல்ல வேண்டாம்.',
    voice_script_moderate: 'கடல் நிலை மிதமானது. குறுகிய தூரத்திற்கு மட்டும் சென்று மதியத்திற்குள் திரும்பவும்.',
  },
  te: {
    app_title: 'సాగర్‌మిత్ర',
    app_subtitle: 'సముద్ర నిర్ణయ & భద్రతా వ్యవస్థ',
    role_fisherman: 'మత్స్యకారుడు',
    role_authority: 'కోస్టల్ అథారిటీ',
    role_researcher: 'సముద్ర పరిశోధన',
    role_data_fusion: 'డేటా గ్రిడ్ B2',
    status_suitable: 'వేటకు సురక్షితమైన సమయం',
    status_moderate: 'మితమైన సముద్రం - జాగ్రత్త',
    status_unsafe: 'ప్రమాదం - సముద్రంలోకి వెళ్లవద్దు',
    safety_score: 'సముద్ర భద్రతా స్కోరు',
    pfz_suitability: 'చేపల లభ్యత జోన్ (PFZ)',
    best_pfz_zone: 'ఉత్తమ చేపల వేట జోన్',
    best_window: 'అనుకూల వేట సమయం',
    recommended_route: 'సురక్షితమైన మార్గం',
    avoid_corridor: 'ప్రమాదకర ప్రాంతాలు',
    marine_anomaly: 'సముద్ర ప్రమాద స్థాయి',
    return_before: 'తిరిగి రావాల్సిన సమయం',
    last_synced: 'చివరి అప్‌డేట్',
    offline_mode_active: 'ఆఫ్‌లైన్ మోడ్ (స్టోర్ చేసిన సమాచారం)',
    listen_audio: 'వినడానికి తాకండి (ఆడియో)',
    ask_ai_placeholder: 'అడగండి (उदा. రేపు వేటకు వెళ్ళవచ్చా?)...',
    btn_submit_catch: 'చేపల వేట వివరాలు',
    btn_sos: 'అత్యవసర SOS సహాయం',
    btn_inspect_reasoning: 'నిర్ణయ కారణం చూడండి',
    cell_b2_title: 'గ్రిడ్ B2 సముద్ర సమాచారం',
    species_likely: 'దొరికే ముఖ్య చేపలు',
    sunlight_mode: 'పగటి వెలుతురు మోడ్',
    bridge_mode: 'రాత్రి మోడ్',
    voice_script_suitable: 'ఈ ఉదయం చేపల వేటకు అనుకూలంగా ఉంది. సెల్ B2 లో 16 కి.మీ నైరుతి దిశలో ఉత్తమ చేపల జోన్ ఉంది. ఉత్తమ సమయం ఉదయం 6 నుండి 10 గంటల వరకు. ఉదయం 11:30 లోపు సురక్షితంగా తిరిగి రండి.',
    voice_script_unsafe: 'హెచ్చరిక! సముద్ర పరిస్థితులు ప్రమాదకరంగా ఉన్నాయి. సముద్రంలోకి వెళ్లవద్దు.',
    voice_script_moderate: 'సముద్ర పరిస్థితులు మధ్యస్థంగా ఉన్నాయి. జాగ్రత్తగా స్వల్ప వేటకు మాత్రమే వెళ్లండి.',
  },
  bn: {
    app_title: 'সাগরমিত্র',
    app_subtitle: 'সামুদ্রিক সিদ্ধান্ত ও নিরাপত্তা ব্যবস্থা',
    role_fisherman: 'মৎস্যজীবী',
    role_authority: 'উপকূলীয় রক্ষী',
    role_researcher: 'সমুদ্র গবেষণা',
    role_data_fusion: 'ডেটা গ্রিড B2',
    status_suitable: 'মাছ ধরার জন্য নিরাপদ',
    status_moderate: 'মাঝারি উত্তাল - সতর্কতা অবলম্বন করুন',
    status_unsafe: 'বিপদ - সমুদ্রে যাবেন না (নো-গো)',
    safety_score: 'নিরাপত্তা স্কোর',
    pfz_suitability: 'সম্ভাব্য মাছ ধরার অঞ্চল (PFZ)',
    best_pfz_zone: 'সেরা মাছের অঞ্চল',
    best_window: 'মাছ ধরার সেরা সময়',
    recommended_route: 'প্রস্তাবিত নিরাপদ পথ',
    avoid_corridor: 'বিপদজনক এলাকা এড়িয়ে চলুন',
    marine_anomaly: 'আবহাওয়া ঝুঁকি স্তর',
    return_before: 'বন্দরে ফেরার সময়',
    last_synced: 'সর্বশেষ তথ্য',
    offline_mode_active: 'অফলাইন মোড (সংরক্ষিত তথ্য)',
    listen_audio: 'বাংলায় শুনুন (অডিও)',
    ask_ai_placeholder: 'জিজ্ঞাসা করুন (যেমন: কাল সকালে মাছ ধরা যাবে কি?)...',
    btn_submit_catch: 'ধরা মাছের বিবরণ দিন',
    btn_sos: 'জরুরী SOS বার্তা',
    btn_inspect_reasoning: 'এআই সিদ্ধান্তের কারণ',
    cell_b2_title: 'গ্রিড সেল B2 টেলিমেট্রি',
    species_likely: 'সম্ভাব্য মাছ',
    sunlight_mode: 'দিনের আলো মোড',
    bridge_mode: 'রাতের মোড',
    voice_script_suitable: 'আজ সকালে মাছ ধরার জন্য পরিস্থিতি অনুকূল। সেরা মাছের অঞ্চলটি দক্ষিণ-পশ্চিমে ১৬ কিমি দূরে সেল B2 তে অবস্থিত। সেরা সময় সকাল ৬টা থেকে ১০টা। সকাল ১১:৩০ এর মধ্যে নিরাপদে বন্দরে ফিরে আসুন।',
    voice_script_unsafe: 'সতর্কতা! সমুদ্র উত্তাল রয়েছে। সমুদ্রে মাছ ধরতে যাবেন না।',
    voice_script_moderate: 'সমুদ্রের অবস্থা মাঝারি। কম সময়ের জন্য যাত্রা করুন এবং দুপুরের আগেই ফিরে আসুন।',
  },
  gu: {
    app_title: 'સાગરમિત્ર',
    app_subtitle: 'દરિયાઈ નિર્ણય અને સુરક્ષા પ્રણાલી',
    role_fisherman: 'માછીમાર',
    role_authority: 'કોસ્ટ ગાર્ડ',
    role_researcher: 'દરિયાઈ સંશોધન',
    role_data_fusion: 'ડેટા ગ્રીડ B2',
    status_suitable: 'માછીમારી માટે સલામત અને અનુકૂળ',
    status_moderate: 'મધ્યમ સ્થિતિ - સાવચેતી રાખો',
    status_unsafe: 'જોખમ - દરિયામાં જશો નહીં (NO-GO)',
    safety_score: 'સુરક્ષા સ્કોર',
    pfz_suitability: 'મત્સ્ય સંભવિત ઝોન (PFZ)',
    best_pfz_zone: 'શ્રેષ્ઠ માછીમારી વિસ્તાર',
    best_window: 'યોગ્ય માછીમારી સમય',
    recommended_route: 'સૂચવેલ સુરક્ષિત માર્ગ',
    avoid_corridor: 'આ જોખમી રસ્તા ટાળો',
    marine_anomaly: 'દરિયાઈ જોખમ સ્તર',
    return_before: 'પરત ફરવાનો સમય',
    last_synced: 'છેલ્લું અપડેટ',
    offline_mode_active: 'ઓફલાઇન મોડ (સાચવેલી માહિતી)',
    listen_audio: 'ગુજરાતીમાં સાંભળો',
    ask_ai_placeholder: 'પૂછો (જેમ કે: શું કાલે સવારે જવાય?)...',
    btn_submit_catch: 'પકડાયેલી માછલી નોંધો',
    btn_sos: 'ઇમરજન્સી SOS',
    btn_inspect_reasoning: 'નિર્ણયનું કારણ જુઓ',
    cell_b2_title: 'ગ્રીડ B2 દરિયાઈ ડેટા',
    species_likely: 'સંભવિત માછલીઓ',
    sunlight_mode: 'દિવસનો તડકો મોડ',
    bridge_mode: 'રાત્રિ મોડ',
    voice_script_suitable: 'આજે સવારે માછીમારી માટે હવામાન અનુકૂળ છે. સેલ B2 માં 16 કિમી દક્ષિણ-પશ્ચિમે શ્રેષ્ઠ વિસ્તાર છે. સવારે 6 થી 10 સુધી શ્રેષ્ઠ સમય છે. ઉત્તરીય શિપિંગ માર્ગ ટાળો અને સવારે 11:30 પહેલાં પાછા ફરો.',
    voice_script_unsafe: 'ચેતવણી! દરિયો ખૂબ તોફાની છે. દરિયામાં જશો નહીં.',
    voice_script_moderate: 'દરિયાની સ્થિતિ સામાન્ય છે. ટૂંકી સફર કરો અને બપોર પહેલાં પાછા આવો.',
  },
  ml: {
    app_title: 'സാഗർമിത്ര',
    app_subtitle: 'മത്സ്യത്തൊഴിലാളി സുരക്ഷാ & തീരുമാന സംവിധാനം',
    role_fisherman: 'മത്സ്യത്തൊഴിലാളി',
    role_authority: 'തീരദേശ സേന',
    role_researcher: 'സമുദ്ര ഗവേഷണം',
    role_data_fusion: 'ഡാറ്റാ ഗ്രിഡ് B2',
    status_suitable: 'കടലിൽ പോകാൻ സുരക്ഷിതം',
    status_moderate: 'മിതമായ കടൽാവസ്ഥ - ജാഗ്രത പാലിക്കുക',
    status_unsafe: 'അപകടം - കടലിൽ പോകരുത്',
    safety_score: 'സുരക്ഷാ സ്കോർ',
    pfz_suitability: 'മത്സ്യ ലഭ്യത മേഖല (PFZ)',
    best_pfz_zone: 'മികച്ച മത്സ്യബന്ധന മേഖല',
    best_window: 'അനുയോജ്യമായ സമയം',
    recommended_route: 'സുരക്ഷിത പാത',
    avoid_corridor: 'ഒഴിവാക്കേണ്ട പാതകൾ',
    marine_anomaly: 'കാലാവസ്ഥാ അപകടസാധ്യത',
    return_before: 'തിരിച്ചെത്തേണ്ട സമയം',
    last_synced: 'അവസാനം ലഭിച്ച വിവരം',
    offline_mode_active: 'ഓഫ്‌ലൈൻ മോഡ്',
    listen_audio: 'മലയാളത്തിൽ കേൾക്കുക (ഓഡിയോ)',
    ask_ai_placeholder: 'ചോദിക്കുക (उदा. നാളെ കടലിൽ പോകാമോ?)...',
    btn_submit_catch: 'ലഭിച്ച മത്സ്യം രേഖപ്പെടുത്തുക',
    btn_sos: 'അടിയന്തര SOS സന്ദേശം',
    btn_inspect_reasoning: 'തീരുമാനത്തിന്റെ കാരണം കാണുക',
    cell_b2_title: 'ഗ്രിഡ് സെൽ B2 വിവരങ്ങൾ',
    species_likely: 'പ്രതീക്ഷിക്കുന്ന മത്സ്യങ്ങൾ',
    sunlight_mode: 'പകൽ മോഡ്',
    bridge_mode: 'രാത്രി മോഡ്',
    voice_script_suitable: 'ഇന്ന് രാവിലെ കടലിൽ പോകാൻ അനുകൂലമാണ്. തെക്ക് പടിഞ്ഞാറ് 16 കി.മീ അകലെ സെൽ B2 ൽ മികച്ച മത്സ്യസാന്നിധ്യമുണ്ട്. രാവിലെ 6 മുതൽ 10 വരെയാണ് അനുയോജ്യമായ സമയം. രാവിലെ 11:30 ന് മുൻപ് തിരിച്ചെത്തുക.',
    voice_script_unsafe: 'മുന്നറിയിപ്പ്! കടൽ പ്രക്ഷുബ്ധമാണ്. കടലിൽ പോകരുത്.',
    voice_script_moderate: 'കടൽാവസ്ഥ സാധാരണമാണ്. ജാഗ്രത പാലിക്കുക.',
  },
  kn: {
    app_title: 'ಸಾಗರಮಿತ್ರ',
    app_subtitle: 'ಮೀನುಗಾರರ ಸಾಗರ ನಿರ್ಧಾರ ಹಾಗೂ ಸುರಕ್ಷತಾ ವ್ಯವಸ್ಥೆ',
    role_fisherman: 'ಮೀನುಗಾರ',
    role_authority: 'ಕರಾವಳಿ ರಕ್ಷಕ ಪಡೆ',
    role_researcher: 'ಸಾಗರ ಸಂಶೋಧನೆ',
    role_data_fusion: 'ಡೇಟಾ ಗ್ರಿಡ್ B2',
    status_suitable: 'ಮೀನುಗಾರಿಕೆಗೆ ಸುರಕ್ಷಿತವಾಗಿದೆ',
    status_moderate: 'ಮಧ್ಯಮ ಪರಿಸ್ಥಿತಿ - ಎಚ್ಚರವಹಿಸಿ',
    status_unsafe: 'ಅಪಾಯ - ಸಮುದ್ರಕ್ಕೆ ಇಳಿಯಬೇಡಿ',
    safety_score: 'ಸುರಕ್ಷತಾ ಅಂಕ',
    pfz_suitability: 'ಮೀನು ಲಭ್ಯತೆಯ ವಲಯ (PFZ)',
    best_pfz_zone: 'ಉತ್ತಮ ಮೀನುಗಾರಿಕಾ ವಲಯ',
    best_window: 'ಸೂಕ್ತ ಸಮಯ',
    recommended_route: 'ಶಿಫಾರಸು ಮಾಡಿದ ಸುರಕ್ಷಿತ ಮಾರ್ಗ',
    avoid_corridor: 'ತಪ್ಪಿಸಬೇಕಾದ ಮಾರ್ಗಗಳು',
    marine_anomaly: 'ಸಾಗರ ಅಪಾಯ ಮಟ್ಟ',
    return_before: 'ಬಂದರಿಗೆ ಮರಳಬೇಕಾದ ಸಮಯ',
    last_synced: 'ಕೊನೆಯ ನವೀಕರಣ',
    offline_mode_active: 'ಆಫ್‌ಲೈನ್ ಮೋಡ್ (ಉಳಿಸಿದ ಮಾಹಿತಿ)',
    listen_audio: 'ಕನ್ನಡದಲ್ಲಿ ಆಲಿಸಿ (ಆಡಿಯೋ)',
    ask_ai_placeholder: 'ಕೇಳಿ (ಉದಾ. ನಾಳೆ ಬೆಳಿಗ್ಗೆ ಮೀನುಗಾರಿಕೆಗೆ ಹೋಗಬಹುದೇ?)...',
    btn_submit_catch: 'ಮೀನುಗಾರಿಕೆ ಮಾಹಿತಿ ದಾಖಲಿಸಿ',
    btn_sos: 'ತುರ್ತು SOS ಎಚ್ಚರಿಕೆ',
    btn_inspect_reasoning: 'ಕಾರಣ ನೋಡಿ',
    cell_b2_title: 'ಗ್ರಿಡ್ B2 ಸಾಗರ ಮಾಹಿತಿ',
    species_likely: 'ಲಭ್ಯವಾಗುವ ಮೀನುಗಳು',
    sunlight_mode: 'ಹಗಲು ಬೆಳಕಿನ ಮೋಡ್',
    bridge_mode: 'ರಾತ್ರಿ ಮೋಡ್',
    voice_script_suitable: 'ಇಂದು ಬೆಳಿಗ್ಗೆ ಮೀನುಗಾರಿಕೆಗೆ ಅನುಕೂಲಕರವಾಗಿದೆ. ಸೆಲ್ B2 ನಲ್ಲಿ 16 ಕಿ.ಮೀ ನೈಋತ್ಯದಲ್ಲಿ ಉತ್ತಮ ಮೀನಿನ ವಲಯವಿದೆ. ಬೆಳಿಗ್ಗೆ 6 ರಿಂದ 10 ಅತ್ಯುತ್ತಮ ಸಮಯ. ಬೆಳಿಗ್ಗೆ 11:30 ರೊಳಗೆ ಬಂದರಿಗೆ ಮರಳಿ.',
    voice_script_unsafe: 'ಎಚ್ಚರಿಕೆ! ಸಮುದ್ರ ಪ್ರಕ್ಷುಬ್ಧವಾಗಿದೆ. ಸಮುದ್ರಕ್ಕೆ ಹೋಗಬೇಡಿ.',
    voice_script_moderate: 'ಸಮುದ್ರ ಸ್ಥಿತಿ ಸಾಧಾರಣವಾಗಿದೆ. ಜಾಗರೂಕರಾಗಿರಿ.',
  },
  or: {
    app_title: 'ସାଗରମିତ୍ର',
    app_subtitle: 'ମତ୍ସ୍ୟଜୀବୀ ସାମୁଦ୍ରିକ ସୁରକ୍ଷା ଓ ନିଷ୍ପତ୍ତି ପ୍ରଣାଳୀ',
    role_fisherman: 'ମତ୍ସ୍ୟଜୀବୀ',
    role_authority: 'ଉପକୂଳ ରକ୍ଷୀ ବାହିନୀ',
    role_researcher: 'ସମୁଦ୍ର ଗବେଷଣା',
    role_data_fusion: 'ଡାଟା ଗ୍ରୀଡ୍ B2',
    status_suitable: 'ମାଛ ଧରିବା ପାଇଁ ଅନୁକୂଳ ଓ ସୁରକ୍ଷିତ',
    status_moderate: 'ମଧ୍ୟମ ପରିସ୍ଥିତି - ସତର୍କ ରୁହନ୍ତୁ',
    status_unsafe: 'ବିପଦ - ସମୁଦ୍ରକୁ ଯାଆନ୍ତୁ ନାହିଁ (NO-GO)',
    safety_score: 'ସୁରକ୍ଷା ସ୍କୋର',
    pfz_suitability: 'ମାଛ ମିଳିବା କ୍ଷେତ୍ର (PFZ)',
    best_pfz_zone: 'ସର୍ବୋତ୍ତମ ମାଛ ଧରିବା ଜୋନ୍',
    best_window: 'ଉପଯୁକ୍ତ ସମୟ',
    recommended_route: 'ସୁରକ୍ଷିତ ରାସ୍ତା',
    avoid_corridor: 'ବିପଦପୂର୍ଣ୍ଣ ଅଞ୍ଚଳ ଏଡ଼ାଇ ଯାଆନ୍ତୁ',
    marine_anomaly: 'ସାମୁଦ୍ରିକ ବିପଦ ସ୍ତର',
    return_before: 'ବନ୍ଦରକୁ ଫେରିବାର ସମୟ',
    last_synced: 'ଶେଷ ଅପଡେଟ୍',
    offline_mode_active: 'ଅଫଲାଇନ୍ ମୋଡ୍ (ସଂରକ୍ଷିତ ତଥ୍ୟ)',
    listen_audio: 'ଓଡ଼ିଆରେ ଶୁଣନ୍ତୁ (ଅଡିଓ)',
    ask_ai_placeholder: 'ପଚାରନ୍ତୁ (ଯେପରି: କାଲି ସକାଳେ ମାଛ ଧରିବାକୁ ଯାଇପାରିବି କି?)...',
    btn_submit_catch: 'ମାଛ ଧରିବା ରିପୋର୍ଟ ଦିଅନ୍ତୁ',
    btn_sos: 'ଜରୁରୀକାଳୀନ SOS',
    btn_inspect_reasoning: 'ନିଷ୍ପତ୍ତିର କାରଣ ଦେଖନ୍ତୁ',
    cell_b2_title: 'ଗ୍ରୀଡ୍ ସେଲ୍ B2 ତଥ୍ୟ',
    species_likely: 'ସମ୍ଭାବ୍ୟ ମାଛ',
    sunlight_mode: 'ଦିନ ଆଲୋକ ମୋଡ୍',
    bridge_mode: 'ରାତି ମୋଡ୍',
    voice_script_suitable: 'ଆଜି ସକାଳେ ମାଛ ଧରିବା ପାଇଁ ପରିସ୍ଥିତି ଅନୁକୂଳ ଅଛି। ଦକ୍ଷିଣ-ପଶ୍ଚିମରେ ୧୬ କିଲୋମିଟର ଦୂରରେ ସେଲ୍ B2 ରେ ସର୍ବୋତ୍ତମ ମାଛ କ୍ଷେତ୍ର ଅଛି। ସକାଳ ୬ ରୁ ୧୦ ଉପଯୁକ୍ତ ସମୟ। ସକାଳ ୧୧:୩୦ ପୂର୍ବରୁ ସୁରକ୍ଷିତ ଭାବେ ଫେରି ଆସନ୍ତୁ।',
    voice_script_unsafe: 'ଚେତାବନୀ! ସମୁଦ୍ର ଅଶାନ୍ତ ଅଛି। ସମୁଦ୍ର ଭିତରକୁ ଯାଆନ୍ତୁ ନାହିଁ।',
    voice_script_moderate: 'ସମୁଦ୍ର ପରିସ୍ଥିତି ମଧ୍ୟମ। ସତର୍କତାର ସହ କମ୍ ଦୂର ଯାଆନ୍ତୁ ଏବଂ ଦ୍ୱିପ୍ରହର ପୂର୍ବରୁ ଫେରନ୍ତୁ।',
  }
};

export const PHONETIC_SCRIPTS: Record<LanguageCode, Record<string, string>> = {
  en: {
    voice_script_suitable: 'Fishing is suitable this morning. Best zone is 16 kilometers southwest in Cell B2 with 87 percent fish probability. Best fishing window is 6 to 10 AM. Avoid the northern shipping corridor and return safely before 11:30 AM.',
    voice_script_unsafe: 'Warning! Sea conditions are dangerous. Wave height and wind exceed safe limits. Do not enter the sea. Stay safely at port.',
    voice_script_moderate: 'Sea conditions are moderate. Undertake only short inshore voyage and return before afternoon when waves increase.',
  },
  hi: {
    voice_script_suitable: 'Aaj subah machhli pakadna surakshit hai. Sabse achha kshetra 16 kilometer dakshin-pashchim Cell B2 mein hai, jahaan 87 percent machhli milne ki sambhavna hai. Subah 6 se 10 baje tak ka samay sarvottam hai. Uttari shipping marg se bachein aur dopehar 11:30 se pehle laut aayein.',
    voice_script_unsafe: 'Chetavani! Samudra mein oonchi lehrein aur tez hawayein hain. Samudra mein na jaayein. Bandar-gaah par hi rahein.',
    voice_script_moderate: 'Samudra ki sthiti madhyam hai. Keval paas ke kshetra mein jaayein aur dopehar se pehle surakshit laut aayein.',
  },
  mr: {
    voice_script_suitable: 'Aaj sakaali maasemaarisathi vaatavaran anukool aahe. Sarvottam matsya kshetra nairutya dishela 16 kilometer antraavar Cell B2 madhye aahe. Uttam vel sakaali 6 te 10 aahe. Uttarekadil motthya jahajaan-cha marg taala aani sakaali 11:30 chya aadhi bandraat parat yaa.',
    voice_script_unsafe: 'Dhokyacha ishaara! Samudraat mothi laat aani sosaatyacha vaara aahe. Samudraat jaau naka. Bandraat-ach thaamba.',
    voice_script_moderate: 'Samudraat madhyam laata aahet. Jaast door jaau naka aani duparpourvi parat yaa.',
  },
  ta: {
    voice_script_suitable: 'Indru kaalai meenpidikka yetradhu. Sirandha meenpidi mandalam 16 kilometer then-maerkil Cell B2 il ulladhu. Kaalai 6 mudhal 10 mani varai sirandha neram. Vadakku kappal paadhaiyai thavirkkavum. Kaalai 11:30 manikkul karai thirumbavum.',
    voice_script_unsafe: 'Echcharikkai! Kadal kodhanthalippaaga ulladhu. Periya alaigal veesugiradhu. Kadalukku sella vendaam.',
    voice_script_moderate: 'Kadal nilai midhamaanadhu. Kurugiya dhoorathirku mattum sendru madhiyadirkul thirumbavum.',
  },
  te: {
    voice_script_suitable: 'Ee udayam chepala vaetaku anukoolamgaa undhi. Cell B2 lo 16 kilometer nairuthi dishalo utthama chepala zone undhi. Udayam 6 nundi 10 varaku anukoola samayam. Udayam 11:30 lopu surakshitamgaa tirigi randi.',
    voice_script_unsafe: 'Heccharika! Samudra paristhithulu pramaadakaramgaa unnaayi. Samudramloki vellavaddhu.',
    voice_script_moderate: 'Samudra paristhithulu madhyasthangaa unnaayi. Jaagrattagaa svalpa vaetaku maatrame vellandi.',
  },
  bn: {
    voice_script_suitable: 'Aaj shokaale maachh dhorar jonyo poristhiti onukool. Shera maachher oncholti dokshin-poshchime 16 kilometer doore Cell B2 te obosthito. Shera shomoy shokal 6 ta theke 10 ta. Shokal 11:30 er moddhye nirapode bondore phire ashun.',
    voice_script_unsafe: 'Shotorkota! Shomudro uttal royechhe. Shomudre jaaben na.',
    voice_script_moderate: 'Shomudrer obostha maajhari. Kom shomoyer jonyo jaatra korun ebong dupurer aagei phire ashun.',
  },
  gu: {
    voice_script_suitable: 'Aaje savaare maachhimaari maate havaamaan anukool chhe. Cell B2 maan 16 kilometer dakshin-pashchime shreshth vistaar chhe. Savaare 6 thi 10 sudhi shreshth samay chhe. Uttariya shipping maarg taalo ane savaare 11:30 pehlaa paachha aavo.',
    voice_script_unsafe: 'Chetavni! Dariyo khoob tofaani chhe. Dariya maan jasho nahin.',
    voice_script_moderate: 'Dariya ni sthiti saamaanya chhe. Tooki safar karo ane bapor pehlaa paachha aavo.',
  },
  ml: {
    voice_script_suitable: 'Innu raavile kadalil pokaan anukoolamaan. Thekku padinjaaru 16 kilometer akale Cell B2 il mikacha matsya saannidhyamundu. Raavile 6 mudhal 10 vareyaan anuyoojyamaaya samayam. Raavile 11:30 nu munpu thirichetthuka.',
    voice_script_unsafe: 'Munnariyippu! Kadal kshobhichirikkukayaan. Kadalil pokaruthu.',
    voice_script_moderate: 'Kadalavastha saadhaaranamaan. Jaagratha paalikkuka.',
  },
  kn: {
    voice_script_suitable: 'Indu beligge meenugaarikege anukoolakaravaagide. Cell B2 nalli 16 kilometer nairuthyadalli utthama meenina valayavide. Beligge 6 rinda 10 atyutthama samaya. Beligge 11:30 rolagae bandarige marali.',
    voice_script_unsafe: 'Eccharike! Samudra prashubdhavagide. Samudrakke hogabedi.',
    voice_script_moderate: 'Samudra sthiti saadhaaranavaagide. Jaagarookaragiri.',
  },
  or: {
    voice_script_suitable: 'Aaji sakaale maachha dharibaa paain paristhiti anukoola achhi. Dakshina-pashchimare 16 kilometer doorare Cell B2 re sarvottama maachha khetra achhi. Sakaala 6 ru 10 upayukta samaya. Sakaala 11:30 poorbaru surakshita bhaabe pheri aasantu.',
    voice_script_unsafe: 'Chetaabani! Samudra ashaanta achhi. Samudra bheetaraku jaaantu naahi.',
    voice_script_moderate: 'Samudra paristhiti madhyama. Satarkatara saha kama doora jaaantu ebam dweeprahara poorbaru pherantu.',
  }
};
